version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - "./.dockerdev/env/db.env"
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile.dev
    command: ash -c "php artisan serve"
    volumes:
      - .:/app_home
    ports:
      - "8000:8000"
    env_file:
      - "./.dockerdev/env/app.env"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
