version: "3"
services:
  rails_template: &rails_template
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile.dev
    image: rails-dev:1.0.0

  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    env_file:
      - "./.dockerdev/env/db.env"
    ports:
      - "3306:3306"

  app:
    <<: *rails_template
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_home
    ports:
      - "3000:3000"
    env_file:
      - "./.dockerdev/env/app.env"
    depends_on:
      - db
    stdin_open: true
    tty: true

  webpacker:
    <<: *rails_template
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app_home
    ports:
      - "3035:3035"
    env_file:
      - "./.dockerdev/env/webpaker.env"
